### ISSUE TITLE
Implement github actions for publishing container image to ghcr

### ISSUE THREAD

**Issue by kaidotio** [raihara3/communication-webar#1]
```
name: SampleApplication
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs: {}
env:
  OWNER: raihara3
jobs:
  publish:
    runs-on: ubuntu-18.04
    env:
      IMAGE_NAME: sample-application
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: /home/runner/.cache/docker-build
          key: ${{ runner.os }}-sample-application-docker-${{ hashFiles('Dockerfile') }}-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-sample-application-docker-
      - uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - run: |
          IMAGE_PATH=ghcr.io/${OWNER}/${IMAGE_NAME}
          TAG=${GITHUB_REF##*/}
          opt=''
          [ -d /home/runner/.cache/docker-build ] && opt='--cache-from type=local,src=/home/runner/.cache/docker-build'
          docker login ghcr.io -u $OWNER -p ${{ secrets.CR_PAT }}
          docker buildx build --output type=docker,name=$IMAGE_PATH:$TAG,push=false ${opt} --cache-to type=local,mode=max,dest=/home/runner/.cache/docker-build .
          docker push $IMAGE_PATH:$TAG
```
